STATO = 0
MAXX = 640
MAXY = 480
offset = 60  # distanza dal bordo
dim = int(MAXX / 100 * 28)  # dimensione aree nere
MINY = 310  # lunghezza dal crop basso
MINY2 = 260  # lunghezza del crop dell'incroci0
CROPSTART = 410 #start del crop
areaValidaMax = 500 #area valida per il nero
areaValidaMin = 200 #area valida per il nero