STATO = 0
MAXX = 640
MAXY = 480
offset = 20  # distanza dal bordo
dim = int(MAXX / 100 * 23)  # dimensione aree nere
MINY = 310  # lunghezza dal crop basso
MINY2 = 260  # lunghezza del crop dell'incroci0
CROPSTART = 410 #start del crop
areaValidaMax = 1000 #area valida per il nero
areaValidaMin = 120 #area valida per il nero